name: Build and test

on:
  push:
    branches: [ "dev_backend**", "dev-backend" ]
  pull_request:
    branches: [ "dev_backend**", "dev-backend" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: List Directories
        run: dir
        
      - name: Restore NuGet packages for backend
        run: nuget restore backend/backend.sln

      - name: Restore NuGet packages for unit tests
        run: nuget restore ControllerUnitTests/ControllerUnitTests.csproj

      - name: Build Backend
        run: msbuild backend/backend.sln /p:platform="Any CPU" /p:configuration=Release

      - name: Run Unit Tests
        run: dotnet test ControllerUnitTests/ControllerUnitTests.csproj --configuration Release

      - name: Build Docker image
        run: docker build -t Dockerfile -f backend/ .
